Writerside/ccs.tree, Writerside/topics/welcome/subsites/events/angel-events.md
added angel-events.md by thebjoredcraft :)
=> added angel-events.md by thebjoredcraft

Writerside/ccs.tree, Writerside/topics/welcome/subsites/events/mining-events.md
added mining-events.md by thebjoredcraft
=> added mining-events.md by thebjoredcraft

Writerside/topics/questions/Fragen.md
added to Fragen.md "Ist der Seed des Servers öffentlich?"
=> added to Fragen.md "Ist der Seed des Servers öffentlich?"

Writerside/ccs.tree, Writerside/redirection-rules.xml, Writerside/topics/community-server-landing-page.topic, Writerside/topics/lobby-server.md, Writerside/topics/support-tickets.md, Writerside/topics/survival-server/servers.md, Writerside/topics/survival-server/support.md, Writerside/topics/team-members.md
added team-members.md, edited servers.md and added support-tickets.md (jetzt im neuem branch)
=> added team-members.md, edited servers.md and added support-tickets.md (jetzt im neuem branch)

Writerside/topics/survival-server/cosmetics/cosmetics.md
=> feat(docs): edited cosmetics page

Writerside/topics/community-server-landing-page.topic, Writerside/topics/event-server/event-server.topic, Writerside/topics/event-server/events/skyblock/skyblock.md, Writerside/topics/survival-server/plots/plots-homepage.topic
Fixed some typos/spelling errors
=> fix(docs): spelling/typos

Writerside/topics/questions/troubleshooting.md
added ids to every tab, used markdown
=> fix(docs):  edited troubleshooting.md

Writerside/topics/event-server/events/anarchy/anarchy-event.md, Writerside/topics/event-server/events/building/building-event.md, Writerside/topics/event-server/events/flatworld/flatworld.md, Writerside/topics/event-server/events/oceanblock/oceanblock.md, Writerside/topics/event-server/events/skyblock/skyblock.md, Writerside/topics/event-server/events/stoneblock/stoneblock-event.md, Writerside/topics/event-server/how-to-take-part-in-an-event.md, Writerside/topics/lobby-server.md
=> fix(docs): edited every event page

Writerside/topics/survival-server/join/join/how-to-join.md
=> fix(docs): edited how-to-join.md

Writerside/topics/survival-server/map-downloads.md
added ids to the tabs, spellings
=> fix(docs): edited map-downloads.md

Writerside/cfg/glossary.xml, Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
Reverts Keviro/community-server-docs#86
=> Revert "fix(docs): edited rank-overview, edited team table, edited application"

Writerside/cfg/glossary.xml, Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
added Tabaluga as Supporter,
edited application box/content
=> fix(docs): edited rank-overview

Writerside/topics/rules/rules.md
=> fix(docs): edited rules.md

Writerside/topics/survival-server/specials/mechanics/mechanics/changed-vanilla-mechanics.md
changed rules for hard and soft despawn range
=> fix(docs): update changed vanilla meachanics

Writerside/ccs.tree, Writerside/topics/survival-server/specials/specials/events/events.md
deleted community Events, removed close badge
=> fix(docs): update (survival server)event page

Writerside/topics/civilisation-event.md
=> fix(docs): update civ- event page

Writerside/topics/survival-server/server/server/servers.md
=> fix(docs): update servers.md

Writerside/topics/survival-server/economy/economy/economy.md
edited content, shop texts were marked as comment to save them for later
=> fix(docs): update economy system

Writerside/topics/support.md
added report ticket type, added tldr in english, edited how to open a ticket(added form info), edited unban ticket type info
=> fix(docs): update support

Writerside/topics/survival-server/plots/create/create/plot-creation.md, Writerside/topics/survival-server/plots/expand/expand/plot-expand.md, Writerside/topics/survival-server/plots/flags/flags/plot-edit-flags.md, Writerside/topics/survival-server/plots/members/members/plot-add-member.md, Writerside/topics/survival-server/plots/misc/misc/plot-other.md, Writerside/topics/survival-server/plots/rename/rename/plot-rename.md, Writerside/topics/survival-server/plots/visualizer/visualizer/plot-visualizer.md
fixed markdown, removed cloed badges
=> fix(docs): update plots

Writerside/topics/survival-server/commands/commands.md
removed unuseable commands, added or renamed new commands
=> fix(docs): update command page

Writerside/topics/rules/mods/mods/verified-mods.md, Writerside/topics/survival-server/specials/specials.md
removed plasmo voice in allowed mods, added simple voice chat in allowed mods, edited special page. Edited plasmo voice to Simple Voice Chat. spellings in specials.md #voicemod
=> fix(docs): voicemod

Writerside/topics/questions/faq.md
edited content, deleted coltent, spellings, typos
=> fix(docs): update faq

Writerside/cfg/glossary.xml, Writerside/topics/rules/rules.md
=> fix(docs): update rules.md

Writerside/ccs.tree, Writerside/labels.list, Writerside/topics/one-chunk.md
added one chunk event page, added img
=> feat(docs): new one chunk event page

Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
spellings in supporter application description
=> fix(docs): update rankoverview

Writerside/topics/rules/mods/mods/verified-mods.md
=> feat(docs): add flashback

Writerside/ccs.tree, Writerside/topics/questions/faq.md, Writerside/topics/survival-server/lightblocks-itemframes-globebannerpatterns/lightblocks-itemframes-globebannerpatterns/light-blocks-and-invisible-item-frames-and-globe-banner-pattern.md
feat(docs): add globe banner pattern
=> feat(docs): add globe banner pattern

Writerside/topics/event-server/events/diamond/diamondevent.md
changed primary-label to event-held
=> fix(docs): updated event label - 400k

Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
=> fix(docs): update rank-overview.md

Writerside/topics/survival-server/join/join/how-to-join.md
=> fix(docs): "dem" -> "den"

Writerside/topics/survival-server/specials/specials/events/events.md
fix(docs): "rechen" -> "rechnen"
=> fix(docs): "rechen" -> "rechnen"

Writerside/topics/support.md
=> fix(docs): update support.md

Writerside/topics/features.md, Writerside/topics/reusablecontent/util.md, Writerside/topics/survival-server/specials/mechanics/mechanics/changed-vanilla-mechanics.md
added snippet to util.md // included snipped in features.md and changed-vanilla-mechanics.md // added subcategory for the util
=> fix(docs): update features.md // update changed-vanilla.mechanics.md

Writerside/topics/rules/mods/mods/verified-mods.md
=> fix(docs): update verified-mods.md

Writerside/topics/questions/troubleshooting.md
=> fix(docs): update troubleshooting.md

Writerside/topics/rules/rules.md
This pull request includes significant updates to the `Writerside/topics/rules/rules.md` file, focusing on clarifying and refining server rules for better readability and enforcement. The most important changes include modifications to the rules on griefing, game modifications, player behavior, and trading.
Clarifications and refinements:
* **Griefing**: Updated the language to clarify that any destruction or theft from other players will result in an immediate ban and emphasized the need for explicit permission for any changes or usage of private areas. [[1]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L21-L50) [[2]](diffhunk://#diff-19685bad04cb7dde549f60435ca124af29b0e3af7f5672727d363e8f9192c633L105-L131)
* **Game Modifications**: Revised the rules …
=> Rework rules

Writerside/topics/civilisation-event.md
updated video url -> there was no thumbnail before
=> fix(docs): update covilisation-event.md

Writerside/topics/survival-server/specials/specials/events/events.md
=> fix(docs): update events.md

Writerside/topics/skills/combat.md, Writerside/topics/skills/farming.md, Writerside/topics/skills/fishing.md, Writerside/topics/skills/mining.md, Writerside/topics/skills/skills.md, Writerside/topics/skills/woodcutting.md
-> fixed how to get experience in mining.md
-> added ids
-> CTR+ALT+L
=> fix(docs): updated skill-pages

Writerside/ccs.tree
fix(docs): fix keviros mistakes at css.tree
=> fix(docs): fix keviros mistakes at css.tree

Writerside/ccs.tree, Writerside/topics/survival-server/join/join/how-to-join.md, Writerside/topics/survival-server/server/server/servers.md
feat(docs): rework how-to-join.md (cleanup, update)
=> feat(docs): rework how-to-join.md (cleanup, update)

Writerside/topics/event-server/how-to-take-part-in-an-event.md
feat(docs): rework how-to-take-part-in-an-event.md
=> feat(docs): rework how-to-take-part-in-an-event.md

Writerside/topics/tilted.md
updated event state from running to held
=> fix(docs): update tilted world event

Writerside/topics/survival-server/join/join/how-to-join.md
fix(docs): bettter and use only "du" instead of switching between "du" and "ihr"
=> fix(docs): bettter and use only "du" instead of switching between "du" and "ihr"

Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
=> fix(docs): update ranko-verview.md

Writerside/ccs.tree, Writerside/labels.list, Writerside/topics/limitless-heights.md
=> feat(docs): new limitless heights event

Writerside/topics/event-server/events/anarchy/anarchy-event.md, Writerside/topics/event-server/events/civilisation/civilisation-event.md, Writerside/topics/event-server/events/flatworld/flatworld.md, Writerside/topics/event-server/events/oceanblock/oceanblock.md, Writerside/topics/event-server/events/onechunk/one-chunk.md, Writerside/topics/event-server/events/skyblock/skyblock.md, Writerside/topics/event-server/events/stoneblock/stoneblock-event.md, Writerside/topics/event-server/events/tilted/tilted.md
added ids to faq on event pages
=> fix(docs): update event pages

Writerside/topics/survival-server/cosmetics/armorstand.md
for whatever reason there were unecessary  >
=> fix(docs): update armorstand.md

Writerside/topics/limitless-heights.md
updated event state to event-held
=> fix(docs): update limitless heights

Writerside/topics/event-server/events/creative2/creative2.md, Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
updated event state to running
=> fix(docs): update creative event

Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
fix(docs): rank-overview: add developer application phase note
=> fix(docs): rank-overview: add developer application phase note

Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
added BobbyCar2612 and Qwoxelias as supporter
=> fix(docs): update team members

Writerside/topics/survival-server/ranks/ranks/ranks-overview.md
Keine Ahnung, ob ich noch was vergessen habe
=> fix: added application tab as external developer

Writerside/topics/event-server/clan/clan-more-info.md
Ich hätte ja gerne ne note gemacht, aber `Paragraph can only contain inline elements`
=> fix: added info to connect a disocrdserver to his clan

Writerside/topics/rules/rules.md
general rule created for harmful, sexist, racist content
=> fix: update rules

Writerside/labels.list, Writerside/topics/event-server/events/anarchy/anarchy-event.md, Writerside/topics/event-server/events/building/building-event.md, Writerside/topics/event-server/events/civilisation/civilisation-event.md, Writerside/topics/event-server/events/creative2/creative2.md, Writerside/topics/event-server/events/diamond/diamondevent.md, Writerside/topics/event-server/events/flatworld/flatworld.md, Writerside/topics/event-server/events/nether/nether-event.md, Writerside/topics/event-server/events/oceanblock/oceanblock.md, Writerside/topics/event-server/events/onechunk/one-chunk.md, Writerside/topics/event-server/events/skyblock/skyblock.md, Writerside/topics/event-server/events/stoneblock/stoneblock-event.md, Writerside/topics/event-server/events/tilted/tilted.md, Writerside/topics/limitless-heights.md
=> fix: remove whitespace in label references for consistency, added labels

Writerside/topics/event-server/events/building/building-event.md, Writerside/topics/survival-server/commands/commands.md, Writerside/topics/survival-server/survival-server.topic
https://github.com/SLNE-Development/community-server-docs/actions/runs/14293419149/job/40057590827
=> fix: update links in building-event and survival-server documentation

Writerside/topics/survival-server/specials/events.md
=> fix(docs): update Easter event content for future adaptation

Writerside/topics/event-server/event-server.topic
order: sorted by date old below newest above
=> fix(docs): added and updated badges for every event

Writerside/ccs.tree, Writerside/topics/current-server-issues.md, Writerside/topics/general-server/join/how-to-join.md
**ONLY MERGE IF SERVER IS AVAILABLE FOR EVERYONE**
=> Fix: reverted server maintance content

Writerside/topics/event-server/events/end-event.md
Merge-After: 2025-06-07T16:55:00[Europe/Berlin]
=> Update primary label reference in end-event documentation

Writerside/topics/event-server/events/end-event.md
Merge-After: 2025-06-08T13:55:00+02:00
=> Update primary label reference for end-event to 'event-running'

Writerside/topics/general-server/rules/rules.md
updated rules regarding harmful content and gambling mechanics e.g. casinos
=> fix(update rules):
